apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: oyron-image-hub
spec:
  environments:
    - name: qa
      build:
        from: main
      egress:
        allowRadix: false
    - name: prod
      egress:
        allowRadix: false
  dnsAppAlias:
    environment: prod
    component: web
  components:
    - name: web
      image: ghcr.io/oyron/radix-test:{imageTagName}
      ports:
        - name: http
          port: 8080
      publicPort: http
      environmentConfig:
        - environment: qa
          imageTagName: v7
      authentication:
        oauth2:
          clientId: ca01531a-2065-448b-8a0f-a667fbbcd1d1
          scope: openid profile email offline_access
  privateImageHubs:
    ghcr.io:
      username: oyron
      email: oyron@equinor.com
      