apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-test
spec:
  environments:
    - name: qa
      build:
        from: main
      egress:
        allowRadix: false
    - name: prod
      egress:
        allowRadix: false
  dnsAppAlias:
    environment: prod
    component: web
  components:
    - name: web
      image: ghcr.io/oyron/radix-test:{imageTagName}
      ports:
        - name: http
          port: 8080
      publicPort: http
      environmentConfig:
        - environment: qa
          imageTagName: v6
      authentication:
        oauth2:
          clientId: ca01531a-2065-448b-8a0f-a667fbbcd1d1
          scope: openid profile email offline_access
          sessionStoreType: redis
          redisStore:
            connectionUrl: redis://redis:6379
    - name: redis
      image: bitnami/redis:latest
      secrets:
        - REDIS_PASSWORD
      ports:
        - name: redis
          port: 6379
  privateImageHubs:
    ghcr.io:
      username: oyron
      email: oyron@equinor.com
      